mule:
  env: "prod"
  anypoint.platform.client_id: "dc9d0865c5704bbbae9907a3c2e35442"

###### System API #####################
api:
  client-id: "4d2df208fbe94927a2144bac16785c00"

###### Box Sys Api #######
box:
  host: "helms-box-framework-prod.usg-w1.gov.cloudhub.io"
  port: "443"
  path: "/api/files"
  timeout: "30000"
  clientId: "jdjnjjp0rpxwliic2wg4kdn9k72gs4w4"
  entityId: "888485330"
  keyAlias: "helms-de-jks-uat"
  connectionTimeout: "1800"
  reconnectionFrequency: "2000"
  reconnectionAttempts: "3"  
  upload:
    action: "upload"
    applicationGroup: "helms-int-nac-orba-exam-import"
    applicationName: "helms-int-nac-orba-exam-import"
    sourceFileLocation: ""
    sourceFileName: ""
    targetFileLocation: "305558534307" ##output?
    targetFileName: ""
    targetInputFileLocation: "305558527107" 



#####SFTP Sys Api ########
mft:
  host: "credentia.files.com"
  port: "22"
  path: "/WA/DOH/WA_NNAAP"
  userName: "WA_DOH"
  identityFile: ""
  timeout: "30000"
  username: ""
  reconnectionFrequency: "2000"
  reconnectionAttempts: "3"
  connectionTimeout: "1800"    
  upload: 
    action: "upload"
    applicationGroup: "hsqa"
    applicationName: "sftp"
    sourceFileName: ""
    sourceFileLocation: "/NACORBAExam/UAT"
    targetFileLocation: "/NACORBAExam/ErrorFilesFromDOH"
    targetErrorFileLocation: "/NACORBAExam/ErrorFilesFromDOH"
    targetFileName: "" 
  delete:
    action: "delete"
    applicationGroup: "hsqa"
    applicationName: "sftp"
  get: 
    action: "get"
    applicationGroup: "hsqa"
    applicationName: "sftp"
    sourceFileLocation: "/NACORBAExam/UAT"
    sourceFileName: "*"

###### Logger System API #####################

logger:
  host: "helms-log-framework-prod.usg-w1.gov.cloudhub.io"
  port: "443"
  path: "/api/logger"
  timeout: "30000"
  applicationName: "helms-int-nac-orba-exam-import"
  durationInSeconds: "256"
  logStep: "Message"
  startMessage: "NAC ORBA Exam Imports Application Started to fetch data from sftp"
  endMessage: "NAC ORBA Exam Imports Application Ended"
  resourceName: "query"
  resourceMethod: "POST"
  email: "Email"
  source: "NAC ORBA Exam"
  statusCode: "SUCCESS"
  transactionId: "unique id for each transaction"
  appName: "469: An error has occurred in the NAC ORBA Exam Imports"
  LogFolderLocation: "305558531907"
  messageTypeLog: "Box"
  messageTypeEmail: "Email"
  emailBodyMessage: "Please check error file in MFT NACORBAExam/ErrorFilesFromDOH."
  toAddress: "DOHDLOITADSCHL@doh.wa.gov"
  infoMessage:
    toAddress: "HSQAReview4@doh.wa.gov,Shannon.McMillan@doh.wa.gov"
  
###### Salesforce System API #####################

salesforce:
  host: "helms-salesforce-credentials-prod.usg-w1.gov.cloudhub.io"
  port: "443"
  createpath: "/api/create"
  upsertpath: "/api/upsert"
  deletepath: "/api/delete"
  querypath: "/api/query"
  timeout: "60000"

#######cron job details ##############################################

scheduler:
  cronExpression: "0 45 21 ? * MON-FRI *"
  timeZone: "PST"
  
#Response Timeout
response:
  timeout: "120000"